vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        entity_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/opticiens'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

